name: AssaultCube Web Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.64

    - name: Verify emcc
      run: emcc -v

    - name: Prepare fake ENet include
      run: |
        mkdir -p fake_includes/enet
        cat > fake_includes/enet/enet.h <<'EOF'
        typedef int ENetHost;
        typedef int ENetAddress;
        typedef int ENetPeer;
        #define enet_initialize() 0
        #define enet_deinitialize()
        #define enet_host_create(...) 0
        #define enet_host_destroy(host)
        #define enet_address_set_host(address, name)
        #define enet_address_set_port(address, port)
        #define enet_host_connect(host, address, channels, data) 0
        #define enet_host_service(host, event, timeout) 0
        EOF

    - name: Apply demo patches
      run: |
        # Stub networking init so sockets are not required
        echo -e "\n#ifdef __EMSCRIPTEN__\nvoid initnetwork() {}\n#endif\n" >> source/src/clientgame.cpp

        # Include Emscripten header in main.cpp
        echo -e "\n#ifdef __EMSCRIPTEN__\n#include <emscripten.h>\n#endif\n" >> source/src/main.cpp

    - name: Build AssaultCube to WebAssembly
      run: |
        mkdir -p web-build
        emcc -I fake_includes source/src/*.cpp source/src/clientgame.cpp \
          -I source/src \
          --preload-file source/packages \
          -O3 -s ASSERTIONS=0 -s ALLOW_MEMORY_GROWTH=1 \
          -s MODULARIZE=1 -s EXPORT_ES6=1 -s ENVIRONMENT=web \
          -s SINGLE_FILE=1 \
          -s USE_ZLIB=1 \
          -o web-build/assaultcube.js

    - name: Create minimal HTML loader
      run: |
        cat > web-build/index.html <<'EOF'
        <!doctype html>
        <html>
        <head><meta charset="utf-8"/><title>AssaultCube Web Demo</title></head>
        <body style="margin:0;overflow:hidden">
          <canvas id="canvas" oncontextmenu="event.preventDefault()"></canvas>
          <script type="module">
            import createModule from "./assaultcube.js";
            createModule().then(Module => {
              console.log("AssaultCube Web Demo ready", Module);
            });
          </script>
        </body>
        </html>
        EOF

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: assaultcube-web-demo
        path: web-build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: assaultcube-web-demo
        path: ./public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
